import sqlmodel

"""delete_idx_gender

Revision ID: 6acca9a777e2
Revises: 5bb594ec21a6
Create Date: 2024-11-24 20:29:36.531618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6acca9a777e2'
down_revision: Union[str, None] = '5bb594ec21a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_gender', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_gender', 'users', ['gender'], unique=False)
    # ### end Alembic commands ###
